"use server";
import "server-only";

import { getOpenAI, withTimeout } from "./openai-client";
import { buildSystemPrompt, buildUserPrompt } from "./prompt-builders";
import { analyzeContent, type ExtractedConcepts } from "./content-analyzer";
import { generateCarouselStructure, structureToSlides, enhanceCarouselSlides } from "./carousel-generator";
import { validateContent, shouldRegenerate, getImprovementInstructions } from "./quality-validator";
import type { BrandVoice, GeneratedContent, ReferenceItem, PastMissionSummary } from "@/lib/types";
import { sleep } from "@/lib/utils";
import { generateImagePrompts, generateImagesForSlides } from "@/lib/image-generator";

async function generateFallbackContent(
  caption: string,
  transcript?: string,
  voice?: BrandVoice,
): Promise<GeneratedContent> {
  const tagLine = voice?.hashtags?.join(" ") || "#BrandVoiceAI";
  const shortCaption = caption.length > 200 ? caption.substring(0, 200) + "..." : caption;
  const base: GeneratedContent = {
    linkedin: `🚀 ${voice?.name || "BrandVoice"} Take:\n\n${shortCaption}\n\n${transcript ? `Video insight: "${transcript.slice(0, 150)}..."` : ""}\n\n${tagLine}`,
    carousel: [
      { heading: "Key Insight", body: shortCaption },
      { heading: "Why It Matters", body: "This content provides valuable insights for creators and developers." },
      { heading: "How To Apply", body: "Take action on these insights to improve your workflow." },
      { heading: "Pro Tip", body: "Adapt these concepts to your specific needs." },
      { heading: "Next Steps", body: voice?.ctaStyle || "Join the conversation!" },
    ],
    threads: `Quick takeaway → ${shortCaption.slice(0, 120)}… ${tagLine}`,
    video_script: `Intro → Hook with this insight\nBody → 2–3 key points\nCTA → ${voice?.ctaStyle || "Join the conversation"}`,
  };
  const slidesWithPrompts = await generateImagePrompts(base.carousel);
  return { ...base, carousel: slidesWithPrompts };
}

export async function generateContentWithVoice({
  caption,
  transcript,
  voice,
  referenceItems,
  pastMissions,
  presetNote,
  targetNotes,
  autoImage = process.env.AUTO_IMAGE_GEN === "true",
}: {
  caption: string;
  transcript?: string;
  voice?: BrandVoice;
  referenceItems?: ReferenceItem[];
  pastMissions?: PastMissionSummary[];
  presetNote?: string;
  targetNotes?: string;
  autoImage?: boolean;
}): Promise<GeneratedContent> {
  if (!process.env.OPENAI_API_KEY) {
    await sleep(600);
    return generateFallbackContent(caption, transcript, voice);
  }

  const openai = await getOpenAI();
  if (!openai) throw new Error("OpenAI client not initialized");

  // First, analyze the content to extract key concepts
  console.log("🔍 Analyzing content for key concepts...");
  const concepts = await analyzeContent(caption, transcript, voice);
  console.log("✅ Extracted concepts:", {
    topics: concepts.mainTopics.length,
    technologies: concepts.technologies.length,
    problems: concepts.problems.length,
    hooks: concepts.hooks.length,
  });

  const systemPrompt = await buildSystemPrompt({
    voice,
    past: (pastMissions ?? []).slice(0, 3),
    refs: (referenceItems ?? []).slice(0, 3),
    concepts,
  });
  const userPrompt = buildUserPrompt({ caption, transcript, presetNote, targetNotes, concepts });

  try {
    const completion = await withTimeout(
      openai.chat.completions.create({
        model: "gpt-4o", // Upgraded from gpt-4o-mini
        messages: [
          { role: "system", content: systemPrompt },
          { role: "user", content: userPrompt },
        ],
        temperature: 0.85, // Increased for more creativity
        max_tokens: 3000, // Increased token limit
        response_format: { type: "json_object" as any },
      }),
      45000, // Increased timeout for gpt-4o
      "Content generation",
    );

    let raw = completion.choices[0]?.message?.content;
    if (!raw) throw new Error("No content generated by OpenAI");

    let parsed: GeneratedContent | null = null;
    let retryCount = 0;
    const maxRetries = 2;

    while (retryCount <= maxRetries && !parsed) {
      try {
        const { GeneratedContentSchema } = await import("@/lib/types");
        parsed = GeneratedContentSchema.parse(JSON.parse(raw)) as GeneratedContent;
        break;
      } catch (parseError) {
        retryCount++;
        if (retryCount > maxRetries) {
          return await generateFallbackContent(caption, transcript, voice);
        }
        const retryPrompt = `Return ONLY a valid JSON object with exactly these fields:\n{\n  "linkedin": "Professional LinkedIn post content",\n  "carousel": [\n    {"heading": "Slide 1", "body": "Content for slide 1"},\n    {"heading": "Slide 2", "body": "Content for slide 2"},\n    {"heading": "Slide 3", "body": "Content for slide 3"},\n    {"heading": "Slide 4", "body": "Content for slide 4"},\n    {"heading": "Slide 5", "body": "Content for slide 5"}\n  ],\n  "threads": "Short Threads post",\n  "video_script": "Video script content"\n}\n\nTransform this content: ${caption}${transcript ? `\n\nTranscript: ${transcript}` : ""}`;

        const retryCompletion = await withTimeout(
          openai.chat.completions.create({
            model: "gpt-4o", // Upgraded from gpt-4o-mini
            messages: [
              { role: "system", content: "You are a JSON generator. Return ONLY valid JSON." },
              { role: "user", content: retryPrompt },
            ],
            temperature: 0.3,
            max_tokens: 3000,
            response_format: { type: "json_object" as any },
          }),
          45000,
          "Content generation retry",
        );
        raw = retryCompletion.choices[0]?.message?.content || raw;
      }
    }

    if (!parsed) throw new Error("Failed to generate valid content after retries");

    if (!parsed.linkedin || !Array.isArray(parsed.carousel) || !parsed.threads || !parsed.video_script) {
      throw new Error("AI response missing required fields");
    }

    // Enhance carousel with specialized structure if needed
    console.log("🎨 Enhancing carousel structure...");
    
    // First normalize the carousel
    parsed.carousel = parsed.carousel.map((s, i: number) => {
      if (typeof s === "string") {
        return { heading: `Slide ${i + 1}`, body: s } as any;
      }
      return s as any;
    });
    
    // Ensure exactly 5 slides
    while (parsed.carousel.length < 5) {
      // If we have concepts, generate better filler slides
      if (concepts && concepts.benefits.length > parsed.carousel.length - 1) {
        const benefitIndex = parsed.carousel.length - 1;
        parsed.carousel.push({
          heading: `Benefit ${parsed.carousel.length}`,
          body: concepts.benefits[benefitIndex] || "Continue discovering more value..."
        } as any);
      } else {
        parsed.carousel.push({ 
          heading: `Slide ${parsed.carousel.length + 1}`, 
          body: "Continue the narrative..." 
        } as any);
      }
    }
    parsed.carousel = parsed.carousel.slice(0, 5);
    
    // Enhance carousel slides with concepts
    parsed.carousel = await enhanceCarouselSlides(parsed.carousel as any, concepts);

    // Validate content quality
    console.log("✅ Validating content quality...");
    const qualityScore = validateContent(parsed, concepts, voice);
    console.log(`📊 Quality Score: ${qualityScore.overall}/100`, {
      specificity: qualityScore.specificity,
      engagement: qualityScore.engagement,
      value: qualityScore.value,
    });

    // If quality is too low, regenerate with improvement instructions
    if (await shouldRegenerate(qualityScore)) {
      console.log("⚠️ Quality below threshold, regenerating with improvements...");
      const improvements = await getImprovementInstructions(qualityScore);
      
      const improvedPrompt = userPrompt + `\n\nIMPORTANT IMPROVEMENTS NEEDED:\n${improvements}`;
      
      try {
        const improvedCompletion = await withTimeout(
          openai.chat.completions.create({
            model: "gpt-4o",
            messages: [
              { role: "system", content: systemPrompt },
              { role: "user", content: improvedPrompt },
            ],
            temperature: 0.75, // Slightly lower for improvement pass
            max_tokens: 3000,
            response_format: { type: "json_object" as any },
          }),
          45000,
          "Content regeneration",
        );

        const improvedRaw = improvedCompletion.choices[0]?.message?.content;
        if (improvedRaw) {
          try {
            const { GeneratedContentSchema } = await import("@/lib/types");
            const improvedParsed = GeneratedContentSchema.parse(JSON.parse(improvedRaw)) as GeneratedContent;
            
            // Use improved version if it parsed successfully
            parsed = improvedParsed;
            
            // Re-enhance carousel
            parsed.carousel = parsed.carousel.map((s, i: number) => {
              if (typeof s === "string") {
                return { heading: `Slide ${i + 1}`, body: s } as any;
              }
              return s as any;
            });
            while (parsed.carousel.length < 5) {
              parsed.carousel.push({ 
                heading: `Slide ${parsed.carousel.length + 1}`, 
                body: concepts.benefits[parsed.carousel.length - 1] || "Continue discovering value..." 
              } as any);
            }
            parsed.carousel = parsed.carousel.slice(0, 5);
            parsed.carousel = await enhanceCarouselSlides(parsed.carousel as any, concepts);
            
            console.log("✅ Content regenerated with improvements");
          } catch (improveError) {
            console.error("Failed to parse improved content, using original", improveError);
          }
        }
      } catch (improveError) {
        console.error("Failed to regenerate content, using original", improveError);
      }
    }

    // Generate context-aware image prompts
    const slidesWithPrompts = await generateImagePrompts(parsed.carousel as any);
    if (!autoImage) {
      (parsed as any).carousel = slidesWithPrompts;
      return parsed;
    }
    const slidesWithImages = await generateImagesForSlides(slidesWithPrompts);
    (parsed as any).carousel = slidesWithImages;
    return parsed;
  } catch (error) {
    throw new Error(error instanceof Error ? `Content generation failed: ${error.message}` : "Unknown generation error");
  }
}

